version: "3.7"

services:
  app:
    container_name: zerodhaapp
    build: .
    restart: on-failure
    depends_on:
      # Our app does not work without our database
      # so this ensures our database is loaded first
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - api:/usr/src/app/
    environment:
      PORT: 8080

  postgres:
    image: postgres:14.1-alpine
    container_name: pgres-db
    restart: always
    volumes:
      # When the PostgresSQL container is started it will run any scripts
      # provided in the `docker-entrypoint-initdb.d` directory, this connects
      # our seed file to that directory so that it gets run
      - database_postgres:/var/lib/postgresql/data
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql

  pgadmin:
    container_name: pgres_pgadmin
    image: "dpage/pgadmin4:6.11"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@testpgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "15433:80"
    restart: unless-stopped

volumes:
  api:
  database_postgres:
