version: "3.7"

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: pgres-db
    restart: always
    environment:
      POSTGRES_USER: "gorm"
      POSTGRES_PASSWORD: "gorm"
      POSTGRES_DB: "gorm"
    ports:
      - "15432:5432"
    volumes:
      # When the PostgresSQL container is started it will run any scripts
      # provided in the `docker-entrypoint-initdb.d` directory, this connects
      # our seed file to that directory so that it gets run
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql

  pgadmin:
    container_name: pgres_pgadmin
    image: "dpage/pgadmin4:6.11"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "15433:80"
    restart: unless-stopped
